Hometask 1.2 - 0
simpletonDL/homework pull request #3
Opened 2017-02-28 13:38 UTC by simpletonDL

2017-03-04 11:25 UTC, jzuken commented
ветки надо бы называть по номеру задачи

2017-03-04 11:29 UTC, jzuken requested changes

2017-03-04 11:29 UTC, jzuken commented on List/src/com/company/List.java
> +class Item {
этого товарища лучше сделать приватным классом внутри списка, за пределами его он никому не нужен

2017-03-04 11:29 UTC, jzuken commented on List/src/com/company/List.java
> +    private Item tail;
нафига списку хранить указатель на хвост? это же не очередь

2017-03-04 11:29 UTC, jzuken commented on List/src/com/company/List.java
> +    private Item ptr1;
а этих надо либо понятно назвать, чтобы видно было, зачем они нужны, либо вообще сделать локальными переменными в методах

2017-03-06 20:33 UTC, simpletonDL commented
Здравствуйте, у меня вопрос по поводу стекового калькулятора. Его просто нужно реализовать или ещё нужно научить его считать конкретно выражения? И если нужно, то какого вида? В смысле, например, "3  4 1 + * 67 + " или нормальное для человека выражения типа " (1 + 2)*3 + 12 "?

2017-03-07 05:14 UTC, jzuken commented
мы писали в прошлом семестре калькулятор, который обычное, инфиксное выражение стеком переводит в постфикс (алгоритм сортировочной станции), а потом постфикс стеком же и считает. предполагается, что тут будет такое же. если кажется сложным, можно просто реализовать подсчёт постфиксного выражения

2017-03-08 08:55 UTC, merged