Hometask_2.1
simpletonDL/homework pull request #4
Opened 2017-03-09 10:11 UTC by simpletonDL

2017-03-09 12:48 UTC, jzuken commented
хорошо бы ещё задачи по папкам в соответствии с ДЗ раскладывать

2017-03-09 12:57 UTC, jzuken requested changes

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/Stack.java
> +
не стоит тут пустые строчки вставлять

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/Stack.java
> +    void show();
смотрю я на этот метод интерфейса и не понимаю, что он делает? оно что, от консоли зависеть будет?

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByArray.java
> +
ещё лишняя строчка

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByArray.java
> +    private int top;
лучше тут их сразу инициализировать

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByArray.java
> +        } else {
else тут можно не писать

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByPointers.java
> +        String value;
лучше явно всегда писать модификаторы доступа

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByPointers.java
> +    private Item bottom;
инициализацию сюда

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByPointers.java
> +        newItem.value = value;
а чтобы такого не писать, Item'у лучше сделать конструктор

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByPointers.java
> +        } else {
зачем писать else после return?

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackCalculator.java
> + * Created by Арсений Терехов on 09.03.2017.
лучше настроить IDE, чтобы она не генерила таких комментариев. толку от них никакого

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/StackCalculator.java
> +public class StackCalculator extends StackByPointers {
а вот это спорный момент. калькулятор разве является стеком?

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +public class MathCalculations {
не, это как-то совсем плохо. я бы сделал класс калькулятора с операцией calculate(String) в интерфейсе, а всё остальное бы спрятал внутрь него

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/ListOneSide.java
> +public class ListOneSide implements List {
это называется SingleLinkedList

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/ListOneSide.java
> +        String value;
модификаторы

2017-03-09 12:57 UTC, jzuken commented on Hometask_2.1/src/com/company/ListOneSide.java
> +            if (ptr1.value == value) {
объекты (и в том числе строки) нельзя так сравнивать, для этого есть метод equals

2017-03-09 14:20 UTC, simpletonDL commented on Hometask_2.1/src/com/company/Stack.java
> +    void show();
Вы про метод show? Если да, то мне нужно изменить имя? Немного не понял

2017-03-09 15:16 UTC, jzuken commented on Hometask_2.1/src/com/company/Stack.java
> +    void show();
а что он делает?

2017-03-09 19:26 UTC, simpletonDL commented on Hometask_2.1/src/com/company/Stack.java
> +    void show();
Ну тип выводит стек в консоль. Переназвал showInConsole.

2017-03-09 20:46 UTC, jzuken commented on Hometask_2.1/src/com/company/Stack.java
> +    void show();
мм, в этой задаче ок, но дальше буду ругать за такие методы. не должен класс, реализующий АТД, выводить ничего никуда

2017-03-13 13:49 UTC, jzuken requested changes

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/List.java
> +    int locale(String value);
locale? это что значит?

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/List.java
> +
лишняя пустая строчка

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/Main.java
> +
и тут лишняя строчка

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/Main.java
> +
и тут

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/Main.java
> +		testStack(stack);
а тут чего отступов больше стало?

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/Main.java
> +	{
фигурная скобка не тут должна быть

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    private String[] orderOperator = {"+", "-", "*", "/"};
если это константа, то надо дописать final. и ещё static имеет смысл, видимо

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +public class MathCalculations {
ну так и класс может переименуем тогда?

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    public int calculute(String expression) {
все методы тут вполне можно сделать статическими, судя по всему

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +            } else if ( token.equals("+") || token.equals("-") || token.equals("*") || token.equals("/") ) {
тут лучше сделать явную функцию isOperation()

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    public int calculute(String expression) {
и этот метод очень большой. не стоит делать методы больше экрана длиной, а лучше вообще не больше 10-20 строк

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    private boolean compareOperator(String operator1, String operator2) {
посмотри на имя типа и на возвращаемое значение. они явно не подходят друг к другу

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    private int indexInArray(String[] array, String toFind) {
это делается через Arrays.asList(array).indexOf(toFind)

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/SingleLinkedList.java
> +
лишняя строчка

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/SingleLinkedList.java
> +                ptr2 = ptr2.next;
нафига заводить сразу два указателя и двигать их? можно же подвинуть один, а потом создать второй и сказать, что он ptr1.next

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/SingleLinkedList.java
> +            ptr1 = head;
это две строки надо объединить

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/SingleLinkedList.java
> +        for (Item ptr1 = head.next; ptr1 != null; ptr1 = ptr1.next) {
а тут есть ptr2, чтобы называть переменную ptr1? вообще её лучше было бы назвать current или как-то так

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByArray.java
> +
лишняя строчка

2017-03-13 13:49 UTC, jzuken commented on Hometask_2.1/src/com/company/StackByPointers.java
> +
лишняя строчка

2017-03-13 13:49 UTC, jzuken commented on howInConsole
> +[33mcommit 6147bb6b73d86030e0b9cb4173d151697f2dfb6d[m
а это что такое?

2017-03-13 22:56 UTC, simpletonDL commented on Hometask_2.1/src/com/company/MathCalculations.java
> +    public int calculute(String expression) {
Я же как раз в самый первый коммит сделал все методы статическими)

2017-03-18 09:34 UTC, jzuken requested changes

2017-03-18 09:34 UTC, jzuken commented on Hometask_2.1/src/com/company/Calculator.java
> +            if ( indexInArray(orderOperator, token) == -1 ) {
пробел лишний, даже два

2017-03-18 09:34 UTC, jzuken commented on Hometask_2.1/src/com/company/Calculator.java
> +import java.lang.reflect.Array;
а этот тут зачем?

2017-03-18 09:34 UTC, jzuken commented on Hometask_2.1/src/com/company/Calculator.java
> +            if ( token.equals("(") ) {
не надо условия пробелами от скобок отделять

2017-03-18 09:34 UTC, jzuken commented on Hometask_2.1/src/com/company/Calculator.java
> +        if (token.equals("+") || token.equals("-") || token.equals("*") || token.equals("/")) return true;
у меня сейчас кровь из глаз потечёт от такого кода. подумай, как это одной строчкой записать, без каких-то условий

2017-03-18 23:40 UTC, simpletonDL commented
Я понял, что не правильно работал с .gitignore. Простите, очень скоро сделаю так, чтобы ветки мержились автоматически.

2017-03-19 10:18 UTC, simpletonDL commented
Все, теперь конфликт разрешен.

2017-03-25 06:04 UTC, merged