Hometask_3.1-0
simpletonDL/homework pull request #6
Opened 2017-03-17 00:14 UTC by simpletonDL

2017-03-18 10:27 UTC, jzuken requested changes

2017-03-18 10:27 UTC, jzuken commented on Hometask_3.1/src/ru/com/bubbleSort.java
> +                    array[j] = array[j+1];
пробелы

2017-03-19 10:25 UTC, simpletonDL commented on Hometask_3.1/src/ru/com/bubbleSort.java
> +                    array[j] = array[j+1];
Какие пробелы?

2017-03-19 11:39 UTC, simpletonDL commented on Hometask_3.1/src/ru/com/bubbleSort.java
> +                    array[j] = array[j+1];
понял

2017-03-25 06:38 UTC, jzuken commented
посмотри на комментарии к коммитам, ты можешь по ним что-то сказать по поводу того, что в этих коммитах изменено? вот и я не могу, а это крайне плохо. заполняй комментарии к коммитам в будущем как-то более осмысленно, пожалуйста

2017-03-25 06:38 UTC, merged