Hometask 4.1
simpletonDL/homework pull request #8
Opened 2017-03-30 23:23 UTC by simpletonDL

2017-04-03 07:18 UTC, jzuken requested changes

2017-04-03 07:18 UTC, jzuken commented on Hometask_4.1/documentation/allclasses-frame.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
это тут явно не нужно

2017-04-03 07:18 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/tests/UniqueListTest.java
> +    private <T> boolean isListsEquals(List<T> A, List<T> B) {
Collections.sort() на оба списка, а потом проверка на equals. всё равно тебе не важно, что списки поменяются

2017-04-03 07:18 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/tests/UniqueListTest.java
> +                fail();
а смысл ловить исключение, чтобы потом упасть? тест и так завершится некорректно, если сгенерируется исключение, которого он не ждёт

2017-04-03 07:18 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/UniqueList.java
> +public class UniqueList<T> implements List<T> {
"На основе него", про которое писалось в условии, не означает, что надо просто скопировать код и поправить под свои нужды, как раз наоборот

2017-04-04 07:54 UTC, simpletonDL commented on Hometask_4.1/src/ru/spbu/terekhow/tests/UniqueListTest.java
> +    private <T> boolean isListsEquals(List<T> A, List<T> B) {
Тут же как раз список List<T> то мой, а не джаваский, названия одни и те же просто, поэтому я написал такую функцию. Или Вы что-то другое имели ввиду?

2017-04-04 15:35 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/tests/UniqueListTest.java
> +    private <T> boolean isListsEquals(List<T> A, List<T> B) {
тогда не занимайся хернёй и переопредели у него equals()

2017-04-04 23:22 UTC, simpletonDL commented on Hometask_4.1/documentation/allclasses-frame.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
Вы про первую строчку? Просто она регенится у всех html файлов.

2017-04-04 23:24 UTC, simpletonDL commented on Hometask_4.1/documentation/allclasses-frame.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
А, или вообще типа не нужно документацию сюда комитить?

2017-04-06 10:04 UTC, jzuken commented on Hometask_4.1/documentation/allclasses-frame.html
> +<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
а зачем? её каждый может сгенерировать

2017-04-06 17:12 UTC, jzuken requested changes

2017-04-06 17:12 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/Main.java
> +import org.omg.CORBA.INTERNAL;
щито?

2017-04-06 17:12 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/Main.java
> +public class Main {
не надо лишних файлов добавлять без нужды

2017-04-06 17:12 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/SingleLinkedList.java
> +public class SingleLinkedList<T> implements List<T> {
javadoc

2017-04-06 17:12 UTC, jzuken commented on Hometask_4.1/src/ru/spbu/terekhow/UniqueList.java
> +    public void insert(int index, T value) throws OutOfTheRange, UnnecessaryAction {
метод insert() никак не переиспользовать?

2017-04-19 17:48 UTC, merged